---
- name: Install alertmanager
  ansible.builtin.import_role:
    name: prometheus.prometheus.alertmanager
  vars:
    alertmanager_version: latest
    alertmanager_receivers:
      - name: email
        email_configs:
          - send_resolved: true
            to: "{{ maintainer_emails }}"
      - name: email_telegram_valli
        email_configs:
          - send_resolved: true
            to: "{{ maintainer_emails }}"
        telegram_configs:
          - send_resolved: true
            bot_token: "{{ telegram_bot_token }}"
            api_url: "https://api.telegram.org"
            chat_id: "{{ telegram_chat_id }}"
            parse_mode: "HTML"
    alertmanager_route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1d
      receiver: email_telegram_valli
      routes:
        - match:
            alertname: Watchdog
          receiver: email
          continue: false
          repeat_interval: 1w
    alertmanager_smtp:
      from: "{{ smtp_from }}"
      smarthost: "{{ smtp_smarthost }}"
      auth_username: "{{ smtp_auth_username }}"
      auth_password: "{{ smtp_auth_password }}"
      auth_secret: ''
      auth_identity: ''
      require_tls: "True"
