---
- name: 4.1 - Compile local packages
  ansible.builtin.shell: "make package/feeds/profiles/{{ libremesh_local_package }}/compile {{ make_nproc }}"
  args:
    chdir: "{{ openwrt_sdk_path }}"
  loop: "{{ libremesh_local_packages }}"
  loop_control:
    loop_var: libremesh_local_package

- name: 4.2 - Generate index of local packages
  ansible.builtin.shell: "make package/index"
  args:
    chdir: "{{ openwrt_sdk_path }}"

