---
- name: Install Grafana
  ansible.builtin.import_role:
    name: cloudalchemy.grafana

# - name: Post install - copy dashboards manually
#   become: yes
#   copy:
#     src: "{{ playbook_dir }}/../../roles/monitoring/grafana/files/"
#     dest: "{{grafana_data_dir}}/dashboards/"

# - name: Chown
#   ansible.builtin.shell: "chown grafana:grafana -R {{grafana_data_dir}}/dashboards/" 
#   notify: restart grafana

# - name: Post install - copy dashboards from repo
#   ansible.builtin.shell: "rm -rf {{grafana_data_dir}}/dashboards/*"

# - name: Post install - prevent git erorrs
#   ansible.builtin.shell: "git config --global --add safe.directory {{grafana_data_dir}}/dashboards/"

# - name: Post install - Clone Dashboards
#   become: yes
#   git:
#     repo: "{{ grafana_dashboards_repository }}"
#     dest: "{{grafana_data_dir}}/dashboards"
#     # single_branch: yes
#     # version: master


