# defaults file for libremesh.libremesh.openwrt_sdk

# Compile options
## Build local_packages only for x86_64, default true
force_openwrt_sdk_build_only_x86_64: true
make_nproc: "-j$(nproc)"

# openwrt sdk paths
openwrt_build_mode: "stable"
openwrt_build_user: "{{ ansible_user }}"
openwrt_dir: /home/{{ openwrt_build_user }}/{{ openwrt_build_mode }}/
openwrt_build_dirname: "libremesh_{{ libremesh_version }}"
openwrt_build_dir: "{{ openwrt_dir }}/{{ openwrt_build_dirname }}"

openwrt_sdk_docker_workdir: "{{ openwrt_dir }}/openwrt_sdk_docker/"
openwrt_sdk_docker_local_packages_sources_mountdir: "{{ openwrt_sdk_docker_workdir }}/local_packages_sources/"
openwrt_sdk_docker_local_packages_sources_dir: /local_packages/
openwrt_sdk_docker_local_packages_overwrite_dir: /builder/feeds/profiles/{{ libremesh_community }}/

openwrt_sdk_docker_image: openwrt/sdk:{{openwrt_target}}-{{openwrt_subtarget}}-v{{openwrt_version}}
openwrt_sdk_docker_container: openwrt_sdk_{{openwrt_target}}-{{openwrt_subtarget}}_v{{openwrt_version}}

libremesh_version_tag: v{{libremesh_version}}
libremesh_feeds: |
  src-git libremesh https://github.com/libremesh/lime-packages.git;{{ libremesh_version_tag }}
  src-git profiles https://github.com/libremesh/network-profiles.git

# Skip options
skip_openwrt_sdk_install_requirements: false