# defaults file for libremesh.libremesh.openwrt_imagebuilder_docker

version_dist: LibreMesh
version_number: "{{ libremesh_version }}"
extra_image_name: ''

# OpenWrt ImageBuilder docker paths
openwrt_build_mode: "stable"
openwrt_build_user: "{{ ansible_user }}"
openwrt_dir: /home/{{ openwrt_build_user }}/{{ openwrt_build_mode }}/
openwrt_build_dirname: "libremesh_{{ libremesh_version }}"
openwrt_build_dir: "{{ openwrt_dir }}/{{ openwrt_build_dirname }}"

openwrt_imagebuilder_docker_workdir: "{{ openwrt_dir }}/openwrt_imagebuilder_{{ openwrt_version }}"
openwrt_imagebuilder_docker_files_dir: "{{ openwrt_imagebuilder_docker_workdir }}/files"
openwrt_imagebuilder_docker_bin_dirname: "{{ openwrt_imagebuilder_docker_workdir }}/images/{{libremesh_community}}/{{libremesh_community_variables_file}}/"

# OpenWrt ImageBuilder docker container and image name
openwrt_imagebuilder_docker_image: openwrt/imagebuilder:{{openwrt_target}}-{{openwrt_subtarget}}-v{{openwrt_version}}
openwrt_imagebuilder_docker_container: openwrt_imagebuilder_{{openwrt_target}}-{{openwrt_subtarget}}_v{{openwrt_version}}

# OpenWrt SDK
libremesh_local_packages: []
openwrt_sdk_local_packages_dir: "{{ openwrt_sdk_path }}/bin/packages/$(ls {{ openwrt_sdk_path }}/bin/packages/)/profiles"
openwrt_imagebuilder_use_openwrt_sdk_non_docker: false

# Force Options
force_openwrt_sdk_rebuild_local_packages: false

# Skip Options
skip_install_openwrt_imagebuilder_docker_requirements: false
skip_build_lime_mac: false
