---
# Special needs for 19.07.10
# - the docker image with the name of openwrt tag is not available for this version: use the name of openwrt branch instead 
# - non existent ./keys directory
# - default user 'build' instead of 'buildbot'

- name: Set default user 'build' and docker image name
  ansible.builtin.set_fact: 
    openwrt_imagebuilder_docker_user: 'build'
    openwrt_imagebuilder_docker_image: openwrt/imagebuilder:{{openwrt_target}}-{{openwrt_subtarget}}-{{openwrt_version}}
