---
- name: Set default user 'buildbot' and docker image name
  ansible.builtin.set_fact: 
    openwrt_imagebuilder_docker_user: 'buildbot'
    openwrt_imagebuilder_docker_image: openwrt/imagebuilder:{{openwrt_target}}-{{openwrt_subtarget}}-v{{openwrt_version}}
    openwrt_imagebuilder_docker_container_workdir: /builder