---
- name: 2.1 - Print debug
  ansible.builtin.include_role:
    name: build
    tasks_from: 1_print_debug.yml

- name: 2.2 - Build
  ansible.builtin.include_tasks: 3_build.yml
  when: openwrt_version != '19.07.10'

- name: 2.2 - Build 19.07.10
  ansible.builtin.include_tasks: 3_build_19.07.10.yml
  when: openwrt_version == '19.07.10'
