---
- name: Append device specific configs to .config
  ansible.builtin.shell: 
    cmd: docker exec {{ openwrt_imagebuilder_docker_container }} sh -c 
      "echo 'CONFIG_{{ device_config }}=y' >> .config"
  loop: "{{ openwrt_device.configs }}"
  loop_control:
    loop_var: device_config