---
- name: 2.1.1 - Build LibreMesh {{ libremesh_version }} {{ openwrt_target }}_{{ openwrt_subtarget }}_{{ openwrt_device.name }}
  ansible.builtin.shell: 
    cmd: docker exec {{ openwrt_imagebuilder_docker_container }} sh -c 
      "make image PROFILE='{{ openwrt_device.name }}'
      PACKAGES='{{ libremesh_version_packages_list | default('') }} 
        {{ libremesh_target_subtarget_packages_list | default('') }} 
        {{ libremesh_devices_packages_list | default('') }}
        {{ libremesh_community_file_target_subtarget_packages_list | default('') }}'
      BIN_DIR='/images/targets/{{ openwrt_target }}_{{ openwrt_subtarget }}' 
      FILES='/files/'
      EXTRA_IMAGE_NAME='{{ extra_image_name | default('') }}'"

- name: 2.1.2 - Build LibreMesh {{ openwrt_device.name }} lime-mac
  include_tasks: 3.2_loop_lime_mac.yml
  when: not skip_build_lime_mac and openwrt_device.lime_mac is defined