---
- name: Clean device specific configs if any
  ansible.builtin.blockinfile: 
    path: "{{ openwrt_imagebuilder_docker_config_dir }}/.config"
    block: ""
    marker: "# {mark} ANSIBLE MANAGED BLOCK device configs"
  ignore_errors: true
