---
# hotfix
- name: Append device specific configs to .config
  ansible.builtin.blockinfile: 
    path: "{{ openwrt_imagebuilder_docker_config_dir }}/.config"
    state: absent
    marker: "# {mark} ANSIBLE MANAGED BLOCK device configs"
