---
- name: 4.1 - Clean previous device configs if any
  ansible.builtin.include_tasks: 4.1.1_configure_device_clean.yml  
  when: openwrt_device.configs is not defined

- name: 4.1 - Apply device specific configs
  ansible.builtin.include_tasks: 4.1.2_configure_device.yml  
  when: openwrt_device.configs is defined

- name: 4.1 - Apply device specific packages
  ansible.builtin.include_tasks: 4.1.3_configure_device_packages.yml  
  when: openwrt_device.packages is defined

- name: Register fact device_full_packages_list
  ansible.builtin.set_fact:
    openwrt_device_full_packages_list: "{{ libremesh_version_packages_list | default('') }} 
        {{ libremesh_target_subtarget_packages_list | default('') }} 
        {{ openwrt_device_packages_list_string | default('') }}
        {{ libremesh_devices_packages_list | default('') }}
        {{ libremesh_community_recipe_target_subtarget_packages_list | default('') }}"

- name: Print debug to file
  blockinfile:
    path: "{{ debug_logfile }}"
    block: |
      openwrt_device: {{ openwrt_device.name | default('') }}
      openwrt_device_packages_list: {{ openwrt_device_full_packages_list | default('') }}
      openwrt_device_configs_list: {{ openwrt_device_configs_list_string | default('') }}
      --------------
    marker: "# DEVICE {{ openwrt_device.name }} {mark} ANSIBLE MANAGED BLOCK"
  delegate_to: localhost
