---
- name: 4.1 - Configure single device
  ansible.builtin.include_tasks: 4.1_configure_single_device.yml  

- name: 4.2 - Build LibreMesh {{ libremesh_version }} {{ openwrt_target }}_{{ openwrt_subtarget }}_{{ openwrt_device.name }}
  ansible.builtin.shell: 
    cmd: docker exec {{ openwrt_imagebuilder_docker_container }} sh -c 
      "make image PROFILE='{{ openwrt_device.name }}'
      PACKAGES='{{ openwrt_device_full_packages_list }}'
      BIN_DIR='/images/{{ openwrt_imagebuilder_docker_container_bin_dir }}' 
      FILES='/files/'
      EXTRA_IMAGE_NAME='{{ extra_image_name | default('') }}'"

# openwrt 19.07.10
- name: 4.3 - workaround to generate device's profiles.json with old openwrt imagebuilder
  ansible.builtin.shell: 
    cmd: docker exec {{ openwrt_imagebuilder_docker_container }} sh -c 
      "mkdir /images/{{ openwrt_imagebuilder_docker_container_bin_dir }}/{{ openwrt_device.name }};
      mv /images/{{ openwrt_imagebuilder_docker_container_bin_dir }}/profiles.json /images/{{ openwrt_imagebuilder_docker_container_bin_dir }}/{{ openwrt_device.name }};"
  when: openwrt_version == '19.07.10'
  ignore_errors: true

- name: 4.4 - Build LibreMesh {{ openwrt_device.name }} lime-mac
  include_tasks: 4.4_loop_lime_mac.yml
  when: not skip_build_lime_mac and openwrt_device.lime_mac is defined