---
- name: 4.1 - Apply device specific configs
  ansible.builtin.include_tasks: 4.1_configure_device.yml  
  when: openwrt_device.configs is defined

- name: 4.2 - Build LibreMesh {{ libremesh_version }} {{ openwrt_target }}_{{ openwrt_subtarget }}_{{ openwrt_device.name }}
  ansible.builtin.shell: 
    cmd: docker exec {{ openwrt_imagebuilder_docker_container }} sh -c 
      "make image PROFILE='{{ openwrt_device.name }}'
      PACKAGES='{{ libremesh_version_packages_list | default('') }} 
        {{ libremesh_target_subtarget_packages_list | default('') }} 
        {{ libremesh_devices_packages_list | default('') }}
        {{ libremesh_community_file_target_subtarget_packages_list | default('') }}'
      BIN_DIR='/images/targets/{{ openwrt_target }}_{{ openwrt_subtarget }}' 
      FILES='/files/'
      EXTRA_IMAGE_NAME='{{ extra_image_name | default('') }}'"

- name: 4.3 - Build LibreMesh {{ openwrt_device.name }} lime-mac
  include_tasks: 4.3_loop_lime_mac.yml
  when: not skip_build_lime_mac and openwrt_device.lime_mac is defined