---
# - name: Assert openwrt version is greater than 19.07
#   ansible.builtin.assert:
#     that: openwrt_version >= 19.07
#     msg: "This module only works with openwrt version greater than 19.07"

- name: Register fact this_role_path
  ansible.builtin.set_fact:
    this_role_path: "{{ role_path }}"
    this_role_name: "{{ role_name }}"

- name: Install Requirements
  ansible.builtin.include_tasks: 0_requirements.yml
  when: not skip_install_openwrt_imagebuilder_docker_requirements

- name: Include all variables
  ansible.builtin.include_role:
    name: build

- name: Register fact build_targets
  ansible.builtin.set_fact:
    build_targets: "{{ openwrt_targets | default(libremesh_devices) }}"

- name: Compile local packages with OpenWrt SDK (increase time of build)
  ansible.builtin.include_tasks: 1_compile_local_packages.yml
  when: libremesh_local_packages != []

- name: Loops build_targets
  ansible.builtin.include_tasks: 2_prepare.yml
  vars:
    openwrt_target: "{{ build_target.openwrt_target }}"
    openwrt_subtarget: "{{ build_target.openwrt_subtarget }}"
    openwrt_devices: "{{ build_target.openwrt_devices | default('all') }}"
  loop: "{{ build_targets }}"
  loop_control:
    loop_var: build_target

