{
 "title": "Public",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "name",
    "label": "Host: ",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "WIFI Host:",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$name\"}, instance)"
    }
   },
   {
    "name": "mesh_stations",
    "label": "Nodo",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", group=\"mesh_stations\"}, host)"
    }
   },
   { "name": "port", "label": "Port", "query": "9090" }
  ]
 },
 "panels": [
  { "title": "Generale rete", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodi Accesi",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodi Spenti",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"$job\"}) - sum(up{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffico in Entrata (Downloads)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"eth0.2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffico in uscita (Uploads)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=\"eth0.2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Velocità massima in entrata (Downloads)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0.2\"}[1m]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Velocità massima in uscita (Uploads)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0.2\"}[1m]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bytes Trasmessi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$mesh_stations",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 0, "y": 5 },
   "repeat": "mesh_stations",
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=\"br-lan\", host=~\"$mesh_stations\"}/1024/1024/1024",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Bytes Ricevuti", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$mesh_stations",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 0, "y": 9 },
   "repeat": "mesh_stations",
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"br-lan\", host=\"$mesh_stations\"}/1000/1000/1000",
     "legendFormat": "{{mesh_stations}}"
    }
   ]
  },
  { "title": "Collegamento migliore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$mesh_stations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 0, "y": 13 },
   "repeat": "mesh_stations",
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (host)(max by (mac)(wifi_station_expected_throughput_kilobits_per_second{ifname=\"wlan0-mesh\", host=\"$mesh_stations\"}/1024))",
     "legendFormat": "{{mac}}"
    }
   ]
  },
  { "title": "Segnale migliore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$mesh_stations",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 0, "y": 17 },
   "repeat": "mesh_stations",
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (host)(wifi_station_signal_dbm{ifname=\"wlan0-mesh\", host=~\"$mesh_stations\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}