{
 "title": "Panoramica Nodi",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "name",
    "label": "Host: ",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "WIFI Host:",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$name\"}, instance)"
    }
   },
   {
    "name": "mesh_stations",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", group=\"mesh_stations\"}, host)"
    }
   },
   { "name": "port", "label": "Port", "query": "9090" }
  ]
 },
 "panels": [
  {
   "title": "Stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodi Up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(up{job=\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nodi Down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{job=\"$job\"}) - sum(up{job=\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Traffico in Entrata (Downloads)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_network_receive_bytes_total{device=\"eth0.2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Traffico in uscita (Uploads)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_network_transmit_bytes_total{device=\"eth0.2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Downloads max speed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{device=\"eth0.2\"}[1m]) * 8",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uploads max speed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{device=\"eth0.2\"}[1m]) * 8",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Transmitted",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$mesh_stations",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 0, "y": 2 },
     "repeat": "mesh_stations",
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_network_transmit_bytes_total{device=\"br-lan\", host=~\"$mesh_stations\"}/1024/1024/1024",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Received",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$mesh_stations",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 0, "y": 3 },
     "repeat": "mesh_stations",
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_network_receive_bytes_total{device=\"br-lan\", host=\"$mesh_stations\"}/1000/1000/1000",
       "legendFormat": "{{mesh_stations}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Best Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$mesh_stations",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 0, "y": 4 },
     "repeat": "mesh_stations",
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (host)(max by (mac)(wifi_station_expected_throughput_kilobits_per_second{ifname=\"wlan0-mesh\", host=\"$mesh_stations\"}/1024))",
       "legendFormat": "{{mac}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Best Signal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$mesh_stations",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 0, "y": 5 },
     "repeat": "mesh_stations",
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (host)(wifi_station_signal_dbm{ifname=\"wlan0-mesh\", host=~\"$mesh_stations\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Wifi Links 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "$mesh_stations - throughput",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
     "repeat": "mesh_stations",
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "avg by (mac)(wifi_station_expected_throughput_kilobits_per_second{ifname=\"wlan0-mesh\", host=\"$mesh_stations\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Devices",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{job=\"$job\"})",
       "legendFormat": " Total"
      },
      {
       "expr": "count(up{job=\"$job\", group=\"mesh_routers\"})",
       "legendFormat": "Mesh Routers"
      },
      {
       "expr": "count(up{job=\"$job\", group=\"mesh_stations\"})",
       "legendFormat": "Mesh Stations"
      },
      {
       "expr": "count(up{job=\"$job\", group=\"home_routers\"})",
       "legendFormat": "Home Routers"
      }
     ]
    },
    {
     "title": "Up Devices",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(up{job=\"$job\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(up{job=\"$job\", group=\"mesh_routers\"})",
       "legendFormat": "Mesh Routers"
      },
      {
       "expr": "sum(up{group=\"mesh_stations\"})",
       "legendFormat": "Mesh Stations"
      },
      {
       "expr": "sum(up{job=\"$job\", group=\"home_routers\"})",
       "legendFormat": "Home Routers"
      }
     ]
    },
    {
     "title": "Down Devices",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{job=\"$job\"}) - sum(up{job=\"$job\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "count(up{job=\"$job\", group=\"mesh_routers\"}) - sum(up{job=\"$job\", group=\"mesh_routers\"})",
       "legendFormat": "Mesh Routers"
      },
      {
       "expr": "count(up{job=\"$job\", group=\"mesh_stations\"}) - sum(up{job=\"$job\", group=\"mesh_stations\"})",
       "legendFormat": "Mesh Stations"
      },
      {
       "expr": "count(up{job=\"$job\", group=\"home_routers\"}) - sum(up{job=\"$job\", group=\"home_routers\"})",
       "legendFormat": "Home Routers"
      }
     ]
    },
    {
     "title": "Wifi Stations - AP Clients",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(wifi_stations{job=\"$job\", group=\"mesh_stations\", ifname!=\"wlan0-mesh\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "wifi_stations{job=\"$job\", group=\"mesh_stations\", ifname!=\"wlan0-mesh\"}",
       "legendFormat": "{{host}} # {{ifname}}"
      }
     ]
    },
    {
     "title": "Wifi Stations - Mesh Clients",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(wifi_stations{job=\"$job\", ifname=\"wlan0-mesh\", group=\"mesh_stations\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "wifi_stations{job=\"$job\", ifname=\"wlan0-mesh\", group=\"mesh_stations\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Up",
     "type": "timeseries",
     "description": "Se la raggiunge prometheus",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "up{job=\"$job\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "description": "Se è viva",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(host)(node_cpu_seconds_total)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Wifi Mesh Clients",
     "type": "timeseries",
     "description": "All connected Mesh Clients",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(wifi_stations{ifname=\"wlan0-mesh\"}) or vector(0)",
       "legendFormat": " Total"
      },
      {
       "expr": "wifi_stations{ifname=\"wlan0-mesh\", group=\"mesh_stations\"} or vector(0)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Wifi AP Clients",
     "type": "timeseries",
     "description": "All connected AP clients, incuding stations with proprietary software",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(wifi_stations{ifname!=\"wlan0-mesh\", group=\"mesh_stations\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "wifi_stations{ifname!=\"wlan0-mesh\", group=\"mesh_stations\"}",
       "legendFormat": "{{host}} # {{ifname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "All devices table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Devices",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "last_over_time(node_uname_info{job=\"$job\"}[$__range]) > 0"
      },
      {
       "expr": "last_over_time(node_openwrt_info{job=\"$job\"}[$__range]) > 0"
      },
      {
       "expr": "up{job=\"$job\"}"
      },
      {
       "expr": "node_time_seconds{job=\"$job\"} - node_boot_time_seconds{job=\"$job\"}"
      },
      {
       "expr": "last_over_time(node_time_seconds{job=\"$job\"}[$__range]) * 1000"
      },
      {
       "expr": "100 * (1 - rate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[$__range])) > 0",
       "legendFormat": "CPU"
      },
      {
       "expr": "(\n  (last_over_time(node_memory_MemTotal_bytes{job=~\"$job\"}[$__range]) - last_over_time(node_memory_MemFree_bytes{job=~\"$job\"}[$__range]) \n  )\n  / \n  (last_over_time(node_memory_MemTotal_bytes{job=~\"$job\"}[$__range]) )\n) * 100"
      },
      {
       "expr": "last_over_time(node_load1{job=\"$job\"}[$__range])"
      },
      {
       "expr": "last_over_time(node_load5{job=\"$job\"}[$__range])"
      },
      {
       "expr": "last_over_time(node_memory_MemTotal_bytes{job=\"$job\"}[$__range])"
      }
     ]
    }
   ]
  },
  {
   "title": "Model and Release",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Model",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (model)(node_openwrt_info)",
       "legendFormat": "{{ model }}"
      }
     ]
    },
    {
     "title": "Release",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (release)(node_openwrt_info)",
       "legendFormat": "{{ release }}"
      }
     ]
    },
    {
     "title": "Model - Release",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (model, release)(node_openwrt_info)",
       "legendFormat": "{{ model }} - {{ release }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Wifi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wifi Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(wifi_network_quality{job=~\"$job\", ifname=\"wlan0-mesh\"}[$__range])"
      }
     ]
    }
   ]
  },
  {
   "title": "Wifi - Links",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$mesh_stations - Links",
     "type": "table",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 25 },
     "repeat": "mesh_stations",
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by (mac)(wifi_station_expected_throughput_kilobits_per_second{ifname=\"wlan0-mesh\", host=\"$mesh_stations\"}/1024)",
       "legendFormat": "Throughput"
      },
      {
       "expr": "avg by (mac)(wifi_station_signal_dbm{ifname=\"wlan0-mesh\", host=\"$mesh_stations\"})",
       "legendFormat": "Signal"
      }
     ]
    },
    {
     "title": "$mesh_stations - Oscillazione",
     "type": "stat",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 25 },
     "repeat": "mesh_stations",
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "options": { "reduceOptions": { "calcs": [ "range" ] } },
     "targets": [
      {
       "expr": "avg by (mac)(wifi_station_signal_dbm{ifname=\"wlan0-mesh\", host=\"$mesh_stations\"})",
       "legendFormat": "{{mac}} - Signal"
      },
      {
       "expr": "avg by (mac)(wifi_station_expected_throughput_kilobits_per_second{ifname=\"wlan0-mesh\", host=\"$mesh_stations\"})",
       "legendFormat": "{{mac}} - Throughput"
      }
     ]
    }
   ]
  },
  {
   "title": "Wifi - Signal and Quality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "$mesh_stations - Signal dbm # wlan0-mesh",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "repeat": "mesh_stations",
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "wifi_station_signal_dbm{ifname=\"wlan0-mesh\", host=\"$mesh_stations\"}",
       "legendFormat": "{{mac}}"
      }
     ]
    },
    {
     "title": "$mesh_stations - Wifi Quality",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "repeat": "mesh_stations",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "wifi_network_quality{host=~\"$mesh_stations\", ifname=\"wlan0-mesh\"}",
       "legendFormat": "{{ifname}}"
      },
      {
       "expr": "wifi_network_quality{host=~\"$mesh_stations\", ifname=\"wlan0-ap\"}",
       "legendFormat": "{{ifname}}"
      },
      {
       "expr": "wifi_network_quality{host=~\"$mesh_stations\", ifname=\"wlan0-apname\"}",
       "legendFormat": "{{ifname}}"
      },
      {
       "expr": "wifi_network_quality{host=~\"$name\", ifname!=\"wlan0-apname\", ifname!=\"wlan0-ap\", ifname!=\"wlan0-mesh\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Wifi - Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$mesh_stations - Throughput # wlan0-mesh",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "repeat": "mesh_stations",
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "wifi_station_expected_throughput_kilobits_per_second{ifname=\"wlan0-mesh\", host=\"$mesh_stations\"}/1024",
       "legendFormat": "{{mac}}"
      }
     ]
    },
    {
     "title": "$mesh_stations - Throughput AP Clients",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "repeat": "mesh_stations",
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "wifi_station_expected_throughput_kilobits_per_second{ifname!=\"wlan0-mesh\", host=\"$mesh_stations\"}/1024",
       "legendFormat": "{{mac}} # {{ifname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic - Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network - All devices",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_network_transmit_bytes_total{device=\"eth0.2\"}",
       "legendFormat": "{{host}}"
      },
      {
       "expr": "node_network_receive_bytes_total{device=\"eth0.2\"}",
       "legendFormat": "{{host}}"
      },
      {
       "expr": "node_network_transmit_bytes_total{device=\"br-lan\"}"
      },
      {
       "expr": "node_network_receive_bytes_total{device=\"br-lan\"}"
      },
      {
       "expr": "({__name__=~\"node_network_transmit_bytes_total\", device=~\"br-lan\"}) + \n({__name__=~\"node_network_receive_bytes_total\", device=~\"br-lan\"})"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{device=\"eth0.2\"}[1m]) * 8"
      },
      {
       "expr": "irate(node_network_receive_bytes_total{device=\"eth0.2\"}[1m]) * 8"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{device=\"br-lan\"}[1m]) * 8"
      },
      {
       "expr": "irate(node_network_receive_bytes_total{device=\"br-lan\"}[1m]) * 8"
      },
      {
       "expr": "\n({__name__=~\"node_network_transmit_bytes_total\", device=~\"eth0.2\"}) + \n({__name__=~\"node_network_receive_bytes_total\", device=~\"eth0.2\"})\n"
      }
     ]
    },
    {
     "title": "WAN - Transmit Speed Max",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{device=\"eth0.2\"}[1m]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "WAN - Receive Speed Max",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{device=\"eth0.2\"}[1m]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "LAN - Transmit Speed Max",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{device=\"br-lan\"}[1d]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "LAN - Receive Speed Max",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{device=\"br-lan\"}[1d]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic - WAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit Bytes Total # eth0.2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_network_transmit_bytes_total{device=\"eth0.2\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Receive Bytes Total # eth0.2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_network_receive_bytes_total{device=\"eth0.2\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Transmit Bytes Speed # eth0.2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{device=\"eth0.2\"}[1m]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Receive Bytes Speed # eth0.2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{device=\"eth0.2\"}[1m]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic - LAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit Bytes Total # br-lan",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (host)(node_network_transmit_bytes_total{device=\"br-lan\"})",
       "legendFormat": "{{device}} {{host}}"
      }
     ]
    },
    {
     "title": "Receive Bytes Total # br-lan",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (host)(node_network_receive_bytes_total{device=\"br-lan\"})",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Transmit Bytes Speed # br-lan",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{device=\"br-lan\"}[1m]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Receive Bytes Speed # br-lan",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{device=\"br-lan\"}[1m]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic - LAN - Ethernet only",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit Bytes Total # eth0.1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_network_transmit_bytes_total{device=\"eth0.1\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Receive Bytes Total # eth0.1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_network_receive_bytes_total{device=\"eth0.1\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Transmit Bytes Speed # eth0.1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{device=\"eth0.1\"}[1m]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Receive Bytes Speed # eth0.1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{device=\"eth0.1\"}[1m]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic - LAN - Wifi only",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit Bytes Total # wlan0-mesh",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_network_transmit_bytes_total{device=\"wlan0-mesh\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Receive bytes total # wlan0-mesh",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_network_receive_bytes_total{device=\"wlan0-mesh\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Transmit Bytes Speed # wlan0-mesh",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{device=\"wlan0-mesh\"}[1m]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Receive Bytes Speed # wlan0-mesh",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{device=\"wlan0-mesh\"}[1m]) * 8",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic - Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Drop",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (host)(\n    irate(node_network_receive_drop_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])\n    +\n    irate(node_network_transmit_drop_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])\n)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "$name - Transmit Bytes Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "repeat": "name",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_network_transmit_bytes_total{host=\"$name\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "$name - Receive Bytes Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "repeat": "name",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_network_receive_bytes_total{host=\"$name\"}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  }
 ]
}