---
blackbox_exporter_version: 0.22.0 # 0.22.0 / 2022-08-02
blackbox_exporter_web_listen_address: "0.0.0.0:9115"
blackbox_exporter_cli_flags: {}
blackbox_exporter_configuration_modules:
  http_2xx_head:
    http:
      method: HEAD
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
      ip_protocol_fallback: false
      preferred_ip_protocol: ip4
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
      valid_status_codes:
        - 200
        - 204
    prober: http
    timeout: 15s
  http_2xx_get:
    http:
      method: GET
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
      ip_protocol_fallback: false
      preferred_ip_protocol: ip4
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
      valid_status_codes:
        - 200
        - 204
        - 302 # Found
    prober: http
    timeout: 15s
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
