---
- name: 1.2.1 - {{ item_lime_mac.lime_mac }} - Define ipv4_host
  shell:
    cmd: echo "$({{ role_path }}/files/mac56-to-ip_host.sh {{ item_lime_mac.lime_mac }} --ip-c-start-from 128)"
  register: ipv4_host

- name: 1.2.2 - {{ item_lime_mac.lime_mac }} - Save ipv4_host
  blockinfile:
    path: "{{ playbook_dir }}/host_vars/{{ item_lime_mac.lime_mac }}.yml"
    block: "ipv4_host: '{{ ipv4_host.stdout }}'"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item_lime_mac.lime_mac }} utils"
    create: yes

- name: 1.2.3 - {{ item_lime_mac.lime_mac }} - Init host_vars common
  blockinfile:
    path: "{{ playbook_dir }}/host_vars/{{ item_lime_mac.lime_mac }}.yml"
    block: |
      hostname: {{ device_hostname }}
      lime_mac: {{ item_lime_mac.lime_mac }}
      ipv4_address: '{{ ipv4_network }}.{{ ipv4_host.stdout }}'
      main_ipv4_address: {{ ipv4_network }}.{{ ipv4_host.stdout }}{{ ipv4_netmask }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item_lime_mac.lime_mac }} common"
    create: yes

- name: 1.2.3 - {{ item_lime_mac.lime_mac }} - Init host_vars device
  blockinfile:
    path: "{{ playbook_dir }}/host_vars/{{ item_lime_mac.lime_mac }}.yml"
    block: |
      target: {{ openwrt_target }}
      subtarget: {{ openwrt_subtarget }}
      device: {{ openwrt_device }}
      openwrt_device_page: https://openwrt.org/start?do=search&id=toh&q={{openwrt_device}}@toh
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item_lime_mac.lime_mac }} device"
    create: yes

- name: 1.2.4 - {{ item_lime_mac.lime_mac }} - Init host_vars config
  blockinfile:
    path: "{{ playbook_dir }}/host_vars/{{ item_lime_mac.lime_mac }}.yml"
    block: |
      config_lime_system: |
        option hostname '{{ device_hostname }}'
      config_lime_wifi: |
        # option channel_5ghz '{% if hostvars[item_lime_mac.lime_mac].channel_5ghz is defined %}{{ hostvars[item_lime_mac.lime_mac].channel_5ghz }}{% else %}{{ default_channel_5ghz }}{% endif %}'
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item_lime_mac.lime_mac }} config"
    create: yes
