---
- name: 1.2.1 - {{ item_lime_mac.lime_mac }} - Define ip_host
  shell:
    cmd: echo "$({{ role_path }}/files/mac56-to-ip_host.sh {{ item_lime_mac.lime_mac }} --ip-c-start-from 128)"
  register: ip_host

- name: 1.2.2 - {{ item_lime_mac.lime_mac }} - Save ip_host
  blockinfile:
    path: "{{ playbook_dir }}/host_vars/{{ item_lime_mac.lime_mac }}.yml"
    block: "ip_host: '{{ ip_host.stdout }}'"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item_lime_mac.lime_mac }} utils"
    create: yes

- name: 1.2.3 - {{ item_lime_mac.lime_mac }} - Init host_vars common
  blockinfile:
    path: "{{ playbook_dir }}/host_vars/{{ item_lime_mac.lime_mac }}.yml"
    block: |
      hostname: {{ item_lime_mac.hostname }}
      lime_mac: {{ item_lime_mac.lime_mac }}
      main_ipv4_address: {{ ip_network }}.{{ ip_host.stdout }}{{ ip_netmask }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item_lime_mac.lime_mac }} common"
    create: yes

- name: 1.2.4 - {{ item_lime_mac.lime_mac }} - Init host_vars config
  blockinfile:
    path: "{{ playbook_dir }}/host_vars/{{ item_lime_mac.lime_mac }}.yml"
    block: |
      config_lime_system: |
        option hostname '{{ item_lime_mac.hostname }}'
      config_lime_wifi: |
        # option channel_5ghz '{% if hostvars[item_lime_mac.lime_mac].channel_5ghz is defined %}{{ hostvars[item_lime_mac.lime_mac].channel_5ghz }}{% else %}{{ default_channel_5ghz }}{% endif %}'
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item_lime_mac.lime_mac }} config"
    create: yes
