---
- ansible.builtin.assert:
    that: 
      - hostvars[groups['wg_server'][0]] is defined
    msg: "wg_server is not defined"

- name: wg-server - Debug - Print to file
  blockinfile:
    path: "{{ wireguard_wg1_devices_list_local_file }}"
    block: "{{ lookup('ansible.builtin.template', 'vpn_wg_peer.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item_lime_mac.lime_mac }}"

- name: wg-server - Add peers to wg server
  become: yes
  blockinfile:
    path: "/etc/wireguard/wg1.conf"
    block: "{{ lookup('ansible.builtin.template', 'vpn_wg_peer.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item_lime_mac.lime_mac }}"
  delegate_to: "{{ hostvars[groups['wg_server'][0]].inventory_hostname }}"
  notify: Restart Wireguard Interface wg1