---

# Debug
openwrt_make_debug_level: '' 

# Community
default_channel_5ghz: 48
default_vpn_wg0_listenport: 51800

# Configuration
target_configs: ''
libremesh_local_packages: []

# Libremesh
version_dist: LibreMesh
version_number: "{{ libremesh_version | default('') }}"
# libremesh_community: libremesh
# libremesh_version: "{{libremesh_release['stable']}}"

libremesh_version_tag: v{{libremesh_version}}
libremesh_community_dir: "{{openwrt_buildroot_dir}}/feeds/profiles/{{libremesh_community}}"
libremesh_feeds: |
  src-git libremesh https://github.com/libremesh/lime-packages.git;{{ libremesh_version_tag }}
  src-git profiles https://github.com/libremesh/network-profiles.git

# Openwrt
openwrt_build_mode: "stable"
openwrt_build_user: "{{ ansible_user }}"
openwrt_dir: /home/{{openwrt_build_user}}/openwrt_build/{{ openwrt_build_mode }}
openwrt_buildroot_dirname: "openwrt_buildroot_{{ openwrt_version }}"
openwrt_buildroot_dir: "{{ openwrt_dir }}/{{ openwrt_buildroot_dirname }}"
openwrt_bin_dir: "images/{{ libremesh_community }}/{{ libremesh_community_variables_file }}/targets/{{openwrt_target}}_{{openwrt_subtarget}}"
openwrt_buildroot_bin_dir: "{{ openwrt_buildroot_dir }}/{{ openwrt_bin_dir }}"


# Overwrite tasks of role ansible_openwrt_buildroot:

# openwrt_task_0_prepare: "{{ this_role_path }}/tasks/0_preflight.yml"
# openwrt_task_1_openwrt_requirements: {{ this_role_path }}/tasks/1_openwrt_requirements.yml
# openwrt_task_2_install_openwrt: {{ this_role_path }}/tasks/2_install_openwrt.yml
openwrt_task_3_add_feeds: "{{ this_role_path }}/tasks/3_libremesh_add_feeds.yml"
# openwrt_task_4_update_install_feeds: {{ this_role_path }}/tasks/4_update_install_feeds.yml
# openwrt_task_5_configure_images: "{{ this_role_path }}/tasks//5_libremesh_configure.yml"
# openwrt_task_5_1_configure_clean: {{ this_role_path }}/tasks/5.1_configure_clean.yml
# openwrt_task_5_2_configure_target: {{ this_role_path }}/tasks/5.2_configure_target.yml
openwrt_task_5_3_configure_custom: "{{ this_role_path }}/tasks/5.3_configure_libremesh_custom.yml"
openwrt_task_6_build_openwrt: "{{ this_role_path }}/tasks/6_build_libremesh.yml"
# openwrt_task_7_post_build: "{{ this_role_path }}/tasks/7_webserver.yml"


# Libremesh config
openwrt_config_image: |
  CONFIG_IMAGEOPT=y
  CONFIG_VERSIONOPT=y
  CONFIG_VERSION_DIST="{{ version_dist }}"
  CONFIG_VERSION_NUMBER="{{ version_number }}"
  CONFIG_KERNEL_BUILD_DOMAIN="buildhost"
  CONFIG_KERNEL_BUILD_USER="builder"

# openwrt_default_target_config_file: libremesh_default_target_config.j2
openwrt_default_config_file: libremesh_default_config.j2