# defaults file for libremesh.libremesh.openwrt_imagebuilder

version_dist: LibreMesh

# OpenWrt ImageBuilder Paths
openwrt_build_mode: "stable"
openwrt_build_user: "{{ ansible_user }}"
openwrt_dir: /home/{{ openwrt_build_user }}/{{ openwrt_build_mode }}/
openwrt_build_dirname: "libremesh_{{ libremesh_version }}"
openwrt_build_dir: "{{ openwrt_dir }}/{{ openwrt_build_dirname }}"

openwrt_imagebuilder_download_dir: "{{ openwrt_dir }}/openwrt_imagebuilder"
openwrt_imagebuilder_bin_dirname: "images/{{ libremesh_community }}/{{ libremesh_community_variables_file }}/targets/{{ openwrt_target }}_{{ openwrt_subtarget }}"
openwrt_imagebuilder_bin_dir: "{{ openwrt_imagebuilder_path }}/{{ openwrt_imagebuilder_bin_dirname }}"

openwrt_imagebuilder_lime_mac_bin_dirname: "images/{{ libremesh_community }}/{{ libremesh_community_variables_file }}/lime-mac/{{item_lime_mac.lime_mac}}"
openwrt_imagebuilder_lime_mac_bin_dir: "{{ openwrt_imagebuilder_path }}/{{ openwrt_imagebuilder_lime_mac_bin_dirname }}"

# Skip Options
skip_build_lime_mac: false
skip_install_openwrt_imagebuilder_requirements: false

force_openwrt_sdk_rebuild_local_packages: false

