---
- name: 1.1 - Clone project
  git:
    repo: "{{ openwrt_firmware_selector_repository }}"
    dest: "{{ openwrt_firmware_selector_download_dir }}"
    single_branch: yes
    version: "{{ openwrt_firmware_selector_version }}"
    update: no

- name: 1.2 - install dependencies
  ansible.builtin.shell: 
    cmd: yarn
  args:
    chdir: "{{ openwrt_firmware_selector_download_dir }}"
